WygWygBundle_homepage:
    pattern:  /
    defaults: { _controller: WygWygBundle:Meetup:showLatest, count: 15 }
    requirements:
        _method:  GET

WygWygBundle_about:
    pattern:  /about
    defaults: { _controller: WygWygBundle:Page:about }
    requirements:
        _method:  GET
WygWygBundle_contact:
    pattern:  /about/contact
    defaults: { _controller: WygWygBundle:Page:contact }
    requirements:
        _method:  GET|POST

WygWygBundle_meetup_showlatest:
    pattern:  /meetups/latest/{count}
    defaults: { _controller: WygWygBundle:Meetup:showLatest, count: 1 }
    requirements:
        _method:  GET
        count: \d+
WygWygBundle_meetup_showall:
    pattern:  /meetups
    defaults: { _controller: WygWygBundle:Meetup:showAll }
    requirements:
        _method:  GET
WygWygBundle_meetup_show:
    pattern:  /meetup/{id}
    defaults: { _controller: WygWygBundle:Meetup:show }
    requirements:
        _method:  GET
        id: \d+

WygWygBundle_meetup_attend:
    pattern:  /meetup/{id}/attend/{status}
    defaults: { _controller: WygWygBundle:Meetup:attend }
    requirements:
        _method:  GET
        id: \d+
        status: yes|no

WygWygBundle_user_show:
    pattern:  /user/{name}
    defaults: { _controller: WygWygBundle:User:show }
    requirements:
        _method:  GET
        name: \w+

WygWygBundle_user_profile:
    pattern:    /profile
    defaults: { _controller: WygWygBundle:User:profile }
    requirements:
        _method:  GET|POST

WygWygBundle_user_register:
    pattern:    /register
    defaults: { _controller: WygWygBundle:User:register }
    requirements:
        _method:  GET|POST

WygWygBundle_user_activate:
    pattern:    /activate
    defaults: { _controller: WygWygBundle:User:activate }
    requirements:
        _method:  GET|POST

WygWygBundle_user_forgot_confirm:
    pattern:    /forgot/confirm/{email}/{key}
    defaults: { _controller: WygWygBundle:User:forgotConfirm }
    requirements:
        _method:  GET|POST
        email: .+
        key: \w+

WygWygBundle_user_forgot:
    pattern:    /forgot
    defaults: { _controller: WygWygBundle:User:forgot }
    requirements:
        _method:  GET|POST


WygWygBundle_meetup_new:
    pattern:  /meetup/new
    defaults: { _controller: WygWygBundle:Meetup:new }
    requirements:
        _method:  GET|POST


