security:
    encoders:
        Wyg\UserBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Wyg\UserBundle\Entity\User, property: username }

    firewalls:
        form_login:
            remember_me:
                key:      secretkeyisthebomb
                lifetime: 3600
                path:     /
                domain:   ~
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        form_login:
            pattern:  ^/login$
            security: false

        main:
            pattern:    /.*
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
            security : true
            anonymous : true

    access_control:
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile,   role: IS_AUTHENTICATED_FULLY }
        - { path: ^/meetup/new,  role: IS_AUTHENTICATED_FULLY }
        - { path: ^/meetup/\d+/attend,  role: IS_AUTHENTICATED_FULLY }
